### PR TITLE
Fixed contract name matching

### LINKED ISSUE #311: Echidna fails to find a contract to analyze in certain cases
Despite [this file](https://github.com/kupl/VeriSmart-benchmarks/blob/master/benchmarks/cve/2018-10706.sol), has a `Token` contract, Echidna cannot find it:

```
$ echidna-test benchmarks/cve/2018-10706.sol Token --config config.yaml
Analyzing contract: /home/g/Data/VeriSmart-benchmarks/benchmarks/cve/2018-10706.sol:ERC20Token
echidna-test: No bytecode found for contract "/home/g/Data/VeriSmart-benchmarks/benchmarks/cve/2018-10706.sol:ERC20Token"
```

### PR DESCRIPTION
**Pull request by ggrieco-tob**
This small PR fixes #311

### CODE REVIEW

File: lib/Echidna/Solidity.hs [hunk 1]
```diff
@@ -170,7 +170,7 @@ loadSpecified name cs = let ensure l e = if l == mempty then throwM e else pure
   where choose []    _        = throwM NoContracts
         choose (c:_) Nothing  = return c
         choose _     (Just n) = maybe (throwM $ ContractNotFound n) pure $
-                                      find (isSuffixOf n . view contractName) cs
+                                      find (isSuffixOf (if count ":" n > 0 then n else ":" `append` n) . view contractName) cs
```
Comment (japesinator) [inline lib/Echidna/Solidity.hs]: `if T.any (== ':') n` is a bit cleaner
